<?php

declare(strict_types=1);

namespace Drupal\aculta_portal\Domain;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Url;
use Drupal\domain\DomainInterface;
use Drupal\domain\DomainNegotiatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/** Resolves stable ACULTA purposes to the canonical Domain entities. */
final class DomainPurposeManager {

  /** Canonical Domain IDs generated by Domain 3.0.1 from production hosts. */
  private const DOMAIN_IDS = [
    'main' => 'aculta_org',
    'account' => 'conta_aculta_org',
    'support' => 'apoio_aculta_org',
    'magazine' => 'coletivo420_aculta_org',
    'wiki' => 'wiki420_aculta_org',
    'shop' => 'loja_aculta_org',
    'courses' => 'cursos_aculta_org',
  ];

  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly DomainNegotiatorInterface $domainNegotiator,
    private readonly ConfigFactoryInterface $configFactory,
    private readonly RequestStack $requestStack,
  ) {}

  /** Returns the current request. */
  private function getCurrentRequest(): ?Request {
    return $this->requestStack->getCurrentRequest();
  }

  /** Returns the purpose associated with the active canonical Domain entity. */
  public function getCurrentPurpose(): ?string {
    $domain = $this->domainNegotiator->getActiveDomain();
    return $domain instanceof DomainInterface ? $this->getPurposeForDomainId($domain->id()) : NULL;
  }

  /** Returns the stable purpose for a configured Domain ID. */
  public function getPurposeForDomainId(string $domainId): ?string {
    $purpose = array_search($domainId, self::DOMAIN_IDS, TRUE);
    return $purpose === FALSE ? NULL : $purpose;
  }

  /**
   * Executa $callback com o Domain do purpose como ativo e restaura o anterior.
   *
   * Serve para avaliar acesso no contexto de origem (por exemplo, a elegibilidade
   * de verbetes da WIKI no sitemap, executado fora do host da WIKI). Não altera a
   * regra de acesso: apenas muda o contexto em que ela é avaliada.
   */
  public function runInPurpose(string $purpose, callable $callback): mixed {
    $domain = $this->getDomain($purpose);
    if ($domain === NULL) {
      return NULL;
    }
    $previous = $this->domainNegotiator->getActiveDomain();
    $this->domainNegotiator->setActiveDomain($domain);
    try {
      return $callback();
    }
    finally {
      if ($previous instanceof DomainInterface) {
        $this->domainNegotiator->setActiveDomain($previous);
      }
    }
  }

  /** Returns a Domain entity for a stable purpose. */
  public function getDomain(string $purpose): ?DomainInterface {
    $id = self::DOMAIN_IDS[$purpose] ?? NULL;
    if ($id === NULL) {
      return NULL;
    }
    $domain = $this->entityTypeManager->getStorage('domain')->load($id);
    return $domain instanceof DomainInterface ? $domain : NULL;
  }

  /** Generates an absolute route URL on a purpose, using Domain Alias context. */
  public function routeUrl(string $purpose, string $routeName, array $parameters = []): ?Url {
    $domain = $this->getDomain($purpose);
    if (!$domain) {
      return NULL;
    }
    $activeDomain = $this->domainNegotiator->getActiveDomain();
    // Never mutate the loaded Domain entity when adapting a non-default alias URL.
    $domain = clone $domain;
    if ($activeDomain && isset($activeDomain->alias)
      && $activeDomain->alias->getEnvironment() !== 'default') {
      $request = $this->getCurrentRequest();
      if ($request) {
        $domain->set('scheme', $request->getScheme());
        $domain->setPath();
      }
    }
    return Url::fromRoute($routeName, $parameters, [
      'absolute' => TRUE,
      'domain' => $domain,
      'https' => $domain->isHttps(),
    ]);
  }

  /** Generates an absolute URL on the configured canonical domain. */
  public function canonicalRouteUrl(string $purpose, string $routeName, array $parameters = []): ?Url {
    $domainId = self::DOMAIN_IDS[$purpose] ?? NULL;
    $domain = $this->getDomain($purpose);
    if ($domainId === NULL || !$domain) {
      return NULL;
    }
    $config = $this->configFactory->get('domain.record.' . $domainId);
    $hostname = $config->get('hostname');
    if (!is_string($hostname) || $hostname === '') {
      return NULL;
    }
    // Domain Alias rewrites loaded Domain entities for the current environment.
    // Restore the canonical hostname from config before creating production URLs.
    $domain = clone $domain;
    $domain->setHostname($hostname);
    $domain->set('scheme', $config->get('scheme') ?: 'https');
    $domain->setPath();
    return Url::fromRoute($routeName, $parameters, [
      'absolute' => TRUE,
      'domain' => $domain,
      'https' => $domain->isHttps(),
    ]);
  }

  /** Generates a same-application path on a purpose domain. */
  /**
   * Absolute canonical URL for a path on a purpose host, always on the
   * production hostname from the domain record (never an alias).
   */
  public function canonicalPathUrl(string $purpose, string $path): ?Url {
    if (!str_starts_with($path, '/') || str_starts_with($path, '//')) {
      return NULL;
    }
    $domainId = self::DOMAIN_IDS[$purpose] ?? NULL;
    $domain = $this->getDomain($purpose);
    if ($domainId === NULL || !$domain) {
      return NULL;
    }
    $config = $this->configFactory->get('domain.record.' . $domainId);
    $hostname = $config->get('hostname');
    if (!is_string($hostname) || $hostname === '') {
      return NULL;
    }
    $domain = clone $domain;
    $domain->setHostname($hostname);
    $domain->set('scheme', $config->get('scheme') ?: 'https');
    $domain->setPath();
    return Url::fromUri(rtrim($domain->getPath(), '/') . $path);
  }

  public function pathUrl(string $purpose, string $path): ?Url {
    if (!str_starts_with($path, '/') || str_starts_with($path, '//')) {
      return NULL;
    }
    $domain = $this->getDomain($purpose);
    if (!$domain) {
      return NULL;
    }
    $activeDomain = $this->domainNegotiator->getActiveDomain();
    // Never mutate the loaded Domain entity when adapting a non-default alias URL.
    $domain = clone $domain;
    if ($activeDomain && isset($activeDomain->alias)
      && $activeDomain->alias->getEnvironment() !== 'default') {
      $request = $this->getCurrentRequest();
      if ($request) {
        $domain->set('scheme', $request->getScheme());
        $domain->setPath();
      }
    }
    // fromUserInput() assembles an internal path against the active request
    // host and does not apply Domain's outbound path processor. Build the
    // absolute URI from the cloned purpose Domain so cross-domain paths keep
    // the requested purpose and alias environment.
    return Url::fromUri(rtrim($domain->getPath(), '/') . $path);
  }

}
