<?php

declare(strict_types=1);

namespace Drupal\aculta_portal\Domain;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Url;
use Drupal\domain\DomainInterface;
use Drupal\domain\DomainNegotiatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;

/** Resolves stable ACULTA purposes to the canonical Domain entities. */
final class DomainPurposeManager {

  /** Canonical Domain IDs generated by Domain 3.0.1 from production hosts. */
  private const DOMAIN_IDS = [
    'main' => 'aculta_org',
    'account' => 'conta_aculta_org',
    'support' => 'apoio_aculta_org',
    'magazine' => 'revista_aculta_org',
    'wiki' => 'wiki_aculta_org',
    'shop' => 'loja_aculta_org',
    'courses' => 'cursos_aculta_org',
  ];

  public function __construct(
    private readonly EntityTypeManagerInterface $entityTypeManager,
    private readonly DomainNegotiatorInterface $domainNegotiator,
    private readonly ConfigFactoryInterface $configFactory,
    private readonly ?RequestStack $requestStack = NULL,
  ) {}

  /** Returns the current request, including for an older compiled container. */
  private function getCurrentRequest(): ?Request {
    return $this->requestStack?->getCurrentRequest() ?? \Drupal::request();
  }

  /** Returns the purpose associated with the active canonical Domain entity. */
  public function getCurrentPurpose(): ?string {
    $domain = $this->domainNegotiator->getActiveDomain();
    return $domain instanceof DomainInterface ? $this->getPurposeForDomainId($domain->id()) : NULL;
  }

  /** Returns the stable purpose for a configured Domain ID. */
  public function getPurposeForDomainId(string $domainId): ?string {
    $purpose = array_search($domainId, self::DOMAIN_IDS, TRUE);
    return $purpose === FALSE ? NULL : $purpose;
  }

  /** Returns a Domain entity for a stable purpose. */
  public function getDomain(string $purpose): ?DomainInterface {
    $id = self::DOMAIN_IDS[$purpose] ?? NULL;
    if ($id === NULL) {
      return NULL;
    }
    $domain = $this->entityTypeManager->getStorage('domain')->load($id);
    return $domain instanceof DomainInterface ? $domain : NULL;
  }

  /** Generates an absolute route URL on a purpose, using Domain Alias context. */
  public function routeUrl(string $purpose, string $routeName, array $parameters = []): ?Url {
    $domain = $this->getDomain($purpose);
    if (!$domain) {
      return NULL;
    }
    $activeDomain = $this->domainNegotiator->getActiveDomain();
    // Domain Alias rewrites the host for the active environment, but keeps the
    // canonical scheme. Local aliases are intentionally HTTP on the current
    // built-in server; production remains canonical HTTPS.
    if ($activeDomain && isset($activeDomain->alias)
      && $activeDomain->alias->getEnvironment() === 'local') {
      $request = $this->getCurrentRequest();
      if ($request) {
        $domain->set('scheme', $request->getScheme());
      }
    }
    return Url::fromRoute($routeName, $parameters, [
      'absolute' => TRUE,
      'domain' => $domain,
      'https' => $domain->isHttps(),
    ]);
  }

  /** Generates an absolute URL on the configured canonical domain. */
  public function canonicalRouteUrl(string $purpose, string $routeName, array $parameters = []): ?Url {
    $domainId = self::DOMAIN_IDS[$purpose] ?? NULL;
    $domain = $this->getDomain($purpose);
    if ($domainId === NULL || !$domain) {
      return NULL;
    }
    $config = $this->configFactory->get('domain.record.' . $domainId);
    $hostname = $config->get('hostname');
    if (!is_string($hostname) || $hostname === '') {
      return NULL;
    }
    // Domain Alias rewrites loaded Domain entities for the current environment.
    // Restore the canonical hostname from config before creating production URLs.
    $domain = clone $domain;
    $domain->setHostname($hostname);
    $domain->set('scheme', $config->get('scheme') ?: 'https');
    $domain->setPath();
    return Url::fromRoute($routeName, $parameters, [
      'absolute' => TRUE,
      'domain' => $domain,
      'https' => $domain->isHttps(),
    ]);
  }

  /** Generates a same-application path on a purpose domain. */
  public function pathUrl(string $purpose, string $path): ?Url {
    if (!str_starts_with($path, '/') || str_starts_with($path, '//')) {
      return NULL;
    }
    $domain = $this->getDomain($purpose);
    if (!$domain) {
      return NULL;
    }
    $activeDomain = $this->domainNegotiator->getActiveDomain();
    if ($activeDomain && isset($activeDomain->alias)
      && $activeDomain->alias->getEnvironment() === 'local') {
      $request = $this->getCurrentRequest();
      if ($request) {
        $domain->set('scheme', $request->getScheme());
      }
    }
    return Url::fromUserInput($path, [
      'absolute' => TRUE,
      'domain' => $domain,
      'https' => $domain->isHttps(),
    ]);
  }

}
