<?php

/**
 * Static gate for the ACCOUNT root (regression barrier for /conta-interna).
 *
 * The account overview is served only at the root of the ACCOUNT Domain. Its internal route
 * path (/conta-interna) must never become a public URL, and no link may be generated by it.
 * This gate reads the sources and reprova:
 * - a second routing entry that uses the internal path;
 * - the request guard of the overview route being removed;
 * - a literal link to the internal path in code, templates, scripts or exported configuration;
 * - a public email confirmation route outside the Portuguese slug family;
 * - a version marker (info.yml) that disagrees with the head of the module CHANGELOG.
 *
 * It does not bootstrap Drupal and does not need vendor/, so it runs in any checkout.
 */

declare(strict_types=1);

$root = dirname(__DIR__);
$module = $root . '/web/modules/custom/aculta_portal';
$internalPath = '/conta-interna';
$failures = [];
$checks = 0;

$read = static function (string $file) use ($root): string {
  $path = $root . '/' . $file;
  $contents = is_file($path) ? file_get_contents($path) : FALSE;
  if ($contents === FALSE) {
    fwrite(STDERR, "CONTA ROOT FAIL: cannot read $file\n");
    exit(1);
  }
  return $contents;
};

// 1. Routing: the internal path belongs only to the overview route.
$routing = $read('web/modules/custom/aculta_portal/aculta_portal.routing.yml');
$checks++;
preg_match_all('#^(?<name>[A-Za-z0-9_.]+):\s*\n\s+path:\s*(?<path>\S+)#m', $routing, $matches, PREG_SET_ORDER);
$usingInternal = [];
foreach ($matches as $match) {
  if (str_starts_with($match['path'], $internalPath)) {
    $usingInternal[] = $match['name'];
  }
}
if ($usingInternal !== ['aculta_portal.dashboard']) {
  $failures[] = 'routing: the internal path ' . $internalPath . ' must belong only to aculta_portal.dashboard; found: ' . implode(', ', $usingInternal);
}

// 2. Email confirmation resend is a public route: Portuguese slug, not the internal path.
$checks++;
if (!preg_match('#aculta_portal\.email_resend:\s*\n\s+path:\s*/confirmar-email/reenviar\s*\n#', $routing)) {
  $failures[] = 'routing: aculta_portal.email_resend must use /confirmar-email/reenviar';
}

// 3. The request guard of the overview route must stay in place.
$checks++;
$subscriber = $read('web/modules/custom/aculta_portal/src/EventSubscriber/DomainPurposeRequestSubscriber.php');
if (!str_contains($subscriber, "'aculta_portal.dashboard' && \$request->getPathInfo() !== '/'")) {
  $failures[] = 'subscriber: DomainPurposeRequestSubscriber::onRequest must return 404 for aculta_portal.dashboard outside the root';
}

// 4. No literal link to the internal path in code, templates, assets or exported configuration.
$scanDirs = [
  'web/modules/custom/aculta_portal/src',
  'web/modules/custom/aculta_portal/templates',
  'web/modules/custom/aculta_portal/js',
  'web/modules/custom/aculta_portal/css',
  'web/modules/custom/aculta_portal/modules/aculta_deployer/src',
  'scripts',
  'config/sync',
];
$allowedConfig = [
  // The ACCOUNT Domain front page resolves the overview internally; it is not a link.
  'config/sync/domain/conta_aculta_org/system.site.yml' => '#^\s*front: /conta-interna\s*$#',
];
foreach ($scanDirs as $dir) {
  $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root . '/' . $dir, FilesystemIterator::SKIP_DOTS));
  foreach ($iterator as $file) {
    if (!$file->isFile() || !preg_match('#\.(php|module|inc|yml|twig|js|mjs|css|json)$#', $file->getFilename())) {
      continue;
    }
    $relative = substr($file->getPathname(), strlen($root) + 1);
    if ($relative === 'scripts/validate-aculta-portal-conta-root.php') {
      continue;
    }
    $checks++;
    $lines = file($file->getPathname(), FILE_IGNORE_NEW_LINES) ?: [];
    foreach ($lines as $number => $line) {
      if (!str_contains($line, $internalPath)) {
        continue;
      }
      // Comments and documentation prose may name the path; code, templates and links may not.
      if (preg_match('~^\s*(?://|\#|\*|/\*)~', $line)) {
        continue;
      }
      if (isset($allowedConfig[$relative]) && preg_match($allowedConfig[$relative], $line)) {
        continue;
      }
      $failures[] = sprintf('%s:%d links the internal path %s', $relative, $number + 1, $internalPath);
    }
  }
}

// 5. Version marker: info.yml must match the head of the module CHANGELOG.
$checks++;
$info = $read('web/modules/custom/aculta_portal/aculta_portal.info.yml');
$changelog = $read('web/modules/custom/aculta_portal/CHANGELOG.md');
preg_match("#^version:\s*'?([^'\n]+)'?#m", $info, $infoMatch);
preg_match('~^## (\S+) —~m', $changelog, $logMatch);
if (($infoMatch[1] ?? NULL) === NULL || ($logMatch[1] ?? NULL) !== ($infoMatch[1] ?? NULL)) {
  $failures[] = sprintf('version: aculta_portal.info.yml (%s) and the CHANGELOG head (%s) disagree', $infoMatch[1] ?? '?', $logMatch[1] ?? '?');
}

if ($failures !== []) {
  foreach ($failures as $failure) {
    fwrite(STDERR, "CONTA ROOT FAIL: $failure\n");
  }
  fwrite(STDERR, sprintf("CONTA ROOT: FAIL (%d failures in %d checks)\n", count($failures), $checks));
  exit(1);
}

echo sprintf("CONTA ROOT: PASS (%d checks; the overview is served only at the ACCOUNT root)\n", $checks);
